# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: App Workflow A

on: [workflow_dispatch]

env:
  flutter_version: "${{ secrets.FLUTTER_VERSION }}"
  java_version: "12.x"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        run: |
          git clone ${{ secrets.GH_ADDRESS }}
          cd ${{ secrets.MAIN_PROJECT_WORKING_DIRECTORY }}
          git config user.name "${{ secrets.GH_USER }}"
          git config user.email "${{ secrets.GH_MAIL }}"
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.java_version }}
          
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
  
      - name: Get dependencies
        working-directory: ${{ secrets.MAIN_PROJECT_WORKING_DIRECTORY }}
        run: flutter pub get
          
      - name: Build app bundle
        working-directory: ${{ secrets.MAIN_PROJECT_WORKING_DIRECTORY }}
        run: flutter build appbundle
        
      - name: Fastlane Release Android
        working-directory: '${{ secrets.MAIN_PROJECT_WORKING_DIRECTORY }}/android'
        run: |
          gem install fastlane
          fastlane deploy
      
